import type { Metadata } from 'next'
import {
  Roboto_Condensed,
  Montserrat,
  Inter,
  Arima,
  Oswald,
  Cascadia_Mono,
  Roboto_Slab,
  Source_Code_Pro,
  Lobster,
  Caveat,
} from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import { CookiesWidget, Footer, Header } from '../widgets'

const roboto = Roboto_Condensed({
  subsets: ['latin'],
  variable: '--font-roboto',
})

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
})

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

const arima = Arima({
  subsets: ['latin'],
  variable: '--font-arima',
})

const oswald = Oswald({
  subsets: ['latin'],
  variable: '--font-oswald',
})

const cascadia = Cascadia_Mono({
  subsets: ['latin'],
  variable: '--font-cascadia',
})

const slab = Roboto_Slab({
  subsets: ['latin'],
  variable: '--font-slab',
})

const source = Source_Code_Pro({
  subsets: ['latin'],
  variable: '--font-source',
})

const lobster = Lobster({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-lobster',
})

const caveat = Caveat({
  subsets: ['latin'],
  variable: '--font-caveat',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${roboto.variable}
          ${montserrat.variable}
          ${inter.variable}
          ${arima.variable}
          ${oswald.variable}
          ${cascadia.variable}
          ${slab.variable}
          ${source.variable}
          ${lobster.variable}
          ${caveat.variable} 
          relative min-h-screen antialiased`}
      >
        <div className="fixed inset-0 -z-10">
          <Image
            src="/background.jpg"
            alt="background"
            fill
            className="object-cover object-center"
            sizes="100vw"
            priority
          />
        </div>
        <Header />
        {children}
        <Footer />
        {/* <CookiesWidget /> */}
      </body>
    </html>
  )
}
