import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import { CookiesWidget, Footer, Header } from '../widgets'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} relative min-h-screen antialiased px-4 py-4 md:px-8 md:py-6 lg:px-12 lg:py-8`}
      >
        <div className="fixed inset-0 -z-10">
          <Image
            src="/background.jpg"
            alt="background"
            fill
            className="object-cover object-center"
            sizes="100vw"
            priority
          />
        </div>
        <Header />
        {children}
        <Footer />
        {/* <CookiesWidget /> */}
      </body>
    </html>
  )
}
